version: '3.3'
services:
    robot-dev:
        network_mode: host
        image: robot-dev
        shm_size: "50gb"
        environment:
            USERNAME: robot
        build:
            context: .
            dockerfile: Dockerfile    
        volumes: [
           "./suites:/opt/robotframework/tests",
           "./scripts:/scripts:/opt/robotframework/scripts",
           ".:/opt/robotframework/work",
           "./reports:/opt/robotframework/reports",
           "/var/run/docker.sock:/var/run/docker.sock"
        ]




